name: DG Release Slack Notification

on:
  push:
    tags:
      - "data-widgets-v*"

jobs:
  notify:
    name: "Slack Notification"
    runs-on: ubuntu-latest
    steps:
      - name: "Notifying Workflow Team on WorkWeiXin"
        run: "echo hello world"
